=== T-m-m-s/Uni/1_anno/html - css - xml - js/ex-xml/Esempi-XML/Playlist.dtd
<!ELEMENT playlist (track+)>
<!ELEMENT track (title, artist+, album?, file, year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT file (encoding, bitrate)>
<!ELEMENT encoding (#PCDATA)>
<!ELEMENT bitrate (#PCDATA)>
<!ATTLIST track id ID #IMPLIED
    genre ( rock | pop | jazz | blues | other) 'other'>
<!ATTLIST file src CDATA #REQUIRED>
<!ATTLIST playlist name CDATA #REQUIRED>
<!ELEMENT year (#PCDATA)>

=== T-m-m-s/Uni/1_anno/WEB/ex-xml/Esempi-XML/Playlist.xml
<?xml version="1.0" ?>
<!DOCTYPE playlist SYSTEM "Playlist.dtd">
<playlist name="Preferiti">
    <track id="t01" genre="rock">
        <title>Anchor</title>
        <artist>Skillet</artist>
        <album>Victorious</album>
        <file src="anchor.mp3">
            <encoding>MP3</encoding>
            <bitrate>160kbps</bitrate>
        </file>
        <year>2020</year>
    </track>
    <track id="t02">
        ...
    </track>
</playlist>
