=== T-m-m-s/Uni/1_anno/html - css - xml - js/Esempi-esami/XML-DTD-II-2021.dtd
<!ELEMENT bibliography (book+)>
<!ELEMENT book (author+,title,subtitle?,year,publisher)>
<!ELEMENT author (name?,surname)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ATTLIST book isbn CDATA #REQUIRED>

=== T-m-m-s/Uni/1_anno/html - css - xml - js/Esempi-esami/XML-DTD-II-2021.xml
<?xml version="1.0"?>
<!DOCTYPE bibliography SYSTEM "XML-DTD-II-2021.dtd">
<bibliography>
  <book isbn="978-0367670566">
    <author>
      <name>Ian</name>
      <surname>Millington</surname>
    </author>
    <title> AI for Games</title>
    <year>2020</year>
    <publisher>CRC Press</publisher>
  </book>
  <book isbn="978-1138363052">
    <author>
      <surname>Egenfeldt-Nielsen</surname>
    </author>
    <author>
      <surname>Smith</surname>
    </author>
    <author>
      <surname>Tosca</surname>
    </author>
    <title>Understanding Video Games</title>
    <subtitle>The Essential Introduction</subtitle>
    <year>2019</year>
    <publisher>Routledge</publisher>
  </book>
</bibliography>
