=== T-m-m-s/Uni/1_anno/html - css - xml - js/Esempi-esami/XML-DTD-IV-2021.dtd
<!ELEMENT movie-collection (movie+)>
<!ELEMENT movie (title,year,director?,actors?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT director (name?,surname)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT actors (actor+)>
<!ELEMENT actor (name?,surname)>
<!ATTLIST actor role (leading|supporting) #IMPLIED>
<!ATTLIST movie format (blu-ray|DVD|digital) #REQUIRED>

=== T-m-m-s/Uni/1_anno/html - css - xml - js/Esempi-esami/XML-DTD-IV-2021.xml
<?xml version="1.0"?>
<!DOCTYPE movie-collection SYSTEM "XML-DTD-IV-2021.dtd">
<movie-collection>
  <movie format="DVD">
    <title>Blade Runner</title>
    <year>1982</year>
    <director>
      <name>Ridley</name>
      <surname>Scott</surname>
    </director>
    <actors>
      <actor role="leading">
        <name>Harrison</name>
        <surname>Ford</surname>
      </actor>
      <actor role="supporting">
        <surname>Young</surname>
      </actor>
    </actors>
  </movie>
  <movie format="blu-ray">
    <title>Blade Runner 2049</title>
    <year>2017</year>
    <director>
      <surname>Villeneuve</surname>
    </director>
    <actors>
      <actor role="leading">
        <surname>Gosling</surname>
      </actor>
    </actors>
  </movie>
  <movie format="digital">
    <title>Ready Player One</title>
    <year>2018</year>
  </movie>
</movie-collection>
