=== T-m-m-s/Uni/1_anno/WEB/ex-xml/Ex_IV.dtd
<!ELEMENT movie-collection (movie+)>
<!ELEMENT movie (title, year, director?, actor*)>
<!ELEMENT actor (name?, surname)>
<!ELEMENT director (name?, surname)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ATTLIST movie format (DVD | blu-ray | digital) #REQUIRED>
<!ATTLIST actor role (leading | supporting) #REQUIRED>

=== T-m-m-s/Uni/1_anno/html - css - xml - js/ex-xml/Ex_V.xml
<?xml version="1.0"?>

<!DOCTYPE movie-collection SYSTEM "Ex_IV.dtd">

<movie-collection>
    <movie format="DVD">
        <title>Blade Runner</title>
        <year>1982</year>
        <director>
            <name>Ridley</name>
            <surname>Scott</surname>
        </director>
        <actor role="leading">
            <name>Harrison</name>
            <surname>Ford</surname>
        </actor>
        <actor role="supporting">
            <surname>Young</surname>
        </actor>
    </movie>

    <movie format="blu-ray">
        <title>Blade Runner 2049</title>
        <year>2017</year>
        <director>
            <surname>Villeneuve</surname>
        </director>
        <actor role="leading">
            <surname>Gosling</surname>
        </actor>
    </movie>

    <movie format="digital">
        <title>Ready Player One</title>
        <year>2018</year>
    </movie>

</movie-collection>
